# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "N:/Development/Dev_Base/netcdf-c-4.9.2;N:/Development/Dev_Base/netcdf-c-4.9.2/msvc")
set(CPACK_CMAKE_GENERATOR "Visual Studio 16 2019")
set(CPACK_COMPONENTS_ALL "Unspecified;headers;libraries;utilities")
set(CPACK_COMPONENT_DEPENDENCIES_DESCRIPTION "Dependencies for this build of NetCDF-C")
set(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "The NetCDF-C user documentation.")
set(CPACK_COMPONENT_HEADERS_DESCRIPTION "Header files for use with NetCDF-C")
set(CPACK_COMPONENT_LIBRARIES_DESCRIPTION "The NetCDF-C Libraries")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_COMPONENT_UTILITIES_DESCRIPTION "The NetCDF-C Utilities")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "netCDF built using CMake")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES ";/expecttds3/;/nocacheremote3/;/nocacheremote4/;/special3/;N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/*;/myhtml/*;/.svn/;my.*\\.sh;/.deps/;/.libs;/html/;.*\\.jar;.*\\.jdl;.*\\.sed;.*\\.proto;.*\\.texi;.*\\.example;Make0;/obsolete/;/unknown/;.*~;.git/")
set(CPACK_INSTALLED_DIRECTORIES "N:/Development/Dev_Base/netcdf-c-4.9.2;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files/netCDF")
set(CPACK_MODULE_PATH "N:/Development/Dev_Base/netcdf-c-4.9.2/cmake/modules/")
set(CPACK_NSIS_CONTACT "support-netcdf@unidata.ucar.edu")
set(CPACK_NSIS_DISPLAY_NAME "NetCDF 4.9.2")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_HELP_LINK "https://www.unidata.ucar.edu/netcdf")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MENU_LINKS "https://www.unidata.ucar.edu/software/netcdf;Unidata Website;https://docs.unidata.ucar.edu/netcdf-c;NetCDF Stable Documentation")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "NetCDF 4.9.2")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://www.unidata.ucar.edu/netcdf")
set(CPACK_OUTPUT_CONFIG_FILE "N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "NetCDF Support <support-netcdf@unidata.ucar.edu>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "NetCDF is a set of software libraries and machine-independent data formats that support the creation, access, and sharing of array-oriented scientific data.")
set(CPACK_PACKAGE_FILE_NAME "netCDF-4.9.2-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.unidata.ucar.edu/software/netcdf/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "netCDF 4.9.2")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "netCDF 4.9.2")
set(CPACK_PACKAGE_NAME "netCDF")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Unidata")
set(CPACK_PACKAGE_VERSION "4.9.2")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/COPYRIGHT.txt")
set(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-3.20/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES ";/expecttds3/;/nocacheremote3/;/nocacheremote4/;/special3/;N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/*;/myhtml/*;/.svn/;my.*\\.sh;/.deps/;/.libs;/html/;.*\\.jar;.*\\.jdl;.*\\.sed;.*\\.proto;.*\\.texi;.*\\.example;Make0;/obsolete/;/unknown/;.*~;.git/")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "N:/Development/Dev_Base/netcdf-c-4.9.2;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "netCDF-4.9.2-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
