# CMake generated Testfile for 
# Source directory: N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test
# Build directory: N:/Development/Dev_Base/netcdf-c-4.9.2/msvc/nc_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(nc_test_t_nc "/nc_test_t_nc")
set_tests_properties(nc_test_t_nc PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_small "/nc_test_tst_small")
set_tests_properties(nc_test_tst_small PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_misc "/nc_test_tst_misc")
set_tests_properties(nc_test_tst_misc PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_norm "/nc_test_tst_norm")
set_tests_properties(nc_test_tst_norm PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_names "/nc_test_tst_names")
set_tests_properties(nc_test_tst_names PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_nofill "/nc_test_tst_nofill")
set_tests_properties(nc_test_tst_nofill PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_nofill2 "/nc_test_tst_nofill2")
set_tests_properties(nc_test_tst_nofill2 PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_nofill3 "/nc_test_tst_nofill3")
set_tests_properties(nc_test_tst_nofill3 PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_meta "/nc_test_tst_meta")
set_tests_properties(nc_test_tst_meta PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_inq_type "/nc_test_tst_inq_type")
set_tests_properties(nc_test_tst_inq_type PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_utf8_phrases "/nc_test_tst_utf8_phrases")
set_tests_properties(nc_test_tst_utf8_phrases PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_global_fillval "/nc_test_tst_global_fillval")
set_tests_properties(nc_test_tst_global_fillval PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_max_var_dims "/nc_test_tst_max_var_dims")
set_tests_properties(nc_test_tst_max_var_dims PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_formats "/nc_test_tst_formats")
set_tests_properties(nc_test_tst_formats PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_def_var_fill "/nc_test_tst_def_var_fill")
set_tests_properties(nc_test_tst_def_var_fill PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_err_enddef "/nc_test_tst_err_enddef")
set_tests_properties(nc_test_tst_err_enddef PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_default_format "/nc_test_tst_default_format")
set_tests_properties(nc_test_tst_default_format PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_atts3 "/nc_test_tst_atts3")
set_tests_properties(nc_test_tst_atts3 PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test_tst_diskless6 "/nc_test_tst_diskless6")
set_tests_properties(nc_test_tst_diskless6 PROPERTIES  FOLDER "tests/" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/CMakeLists.txt;2161;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;87;add_bin_test;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
add_test(nc_test "/nc_test")
set_tests_properties(nc_test PROPERTIES  _BACKTRACE_TRIPLES "N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;90;ADD_TEST;N:/Development/Dev_Base/netcdf-c-4.9.2/nc_test/CMakeLists.txt;0;")
